name: Generate vibrant snake

on:
  schedule:
    - cron: "30 18 * * *"     # runs daily at 18:30 UTC (~00:00 IST+1)
  workflow_dispatch:          # manual run
  push:
    branches: ["main"]        # change to "master" if your repo uses that

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate vibrant snake svgs/gifs
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-neon.svg?color_snake=#ff00ff&color_dots=#00ffff&palette=github-light
            dist/snake.gif
            dist/snake-dark.gif?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
