name: Generate Snake Animation

on:
  schedule: # Run daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: your-username
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
